pg_db:
    name: "postgres"
    host: "postgres"
    port: "5432"
    username: "ruslan"

server:
    host: "localhost"
    port: "8880"
    timeout: "4s"
    idle_timeout: "60s"
    username: "ruslan"

kafka:
    addr: "kafka:9092"
